Rails/p011/config/routes.rb
Rails.application.routes.draw do
  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get   'questionary_results/calc/:id', to: 'questionary_results#calc'
  get   'questionary_choices/new/:id',  to: 'questionary_choices#new'
  get   'questionary_items/new/:id',    to: 'questionary_items#new'
  post  'questionaries/:id',            to: 'questionaries#sendform'
end

Rails/p011/app/models/questionary.rb
class Questionary < ApplicationRecord
    # 従データ：質問内容 / 質問結果
    has_many :questionary_item
    has_many :questionary_result

    # 全データが存在することが必要
    validates :title, :description, :deadline, presence: {
        message: 'の存在が要請されています。'
    }
end

Rails/p011/app/controllers/questionaries_controller.rb
class QuestionariesController < ApplicationController
  before_action :set_questionary, only: [:show, :edit, :update, :destroy]

  # GET /questionaries
  # GET /questionaries.json
  def index
    @questionaries = Questionary.all.order("created_at desc")
  end

  # GET /questionaries/1
  # GET /questionaries/1.json
  def show
  end


  # フォームの送信
  def sendform
    # 変数設定
    id = params[:id]
    result = 'question_id:' + id

    100.times{ |i|
      # ラジオボタン情報をテキスト化して保存
      str = "r" + (i+1).to_s
      if params[str] == nil
        result += "," + str + ":0"
      else
        result += "," + str + ":" + params[str]
      end
    }

    # 結果の設定
    obj = QuestionaryResult.new
    obj.questionary_id = id
    obj.result = result
    obj.save!
    redirect_to '/questionaries'
  end


  # GET /questionaries/new
  def new
    @questionary = Questionary.new
  end

  # GET /questionaries/1/edit
  def edit
  end

  # POST /questionaries
  # POST /questionaries.json
  def create
    @questionary = Questionary.new(questionary_params)

    respond_to do |format|
      if @questionary.save
        format.html { redirect_to '/questionary_items/new/' + @questionary.id.to_s, notice: '質問を無事投稿しました。' }
        format.json { render :show, status: :created, location: @questionary }
      else
        format.html { render :new }
        format.json { render json: @questionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionaries/1
  # PATCH/PUT /questionaries/1.json
  def update
    respond_to do |format|
      if @questionary.update(questionary_params)
        format.html { redirect_to @questionary, notice: 'Questionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionary }
      else
        format.html { render :edit }
        format.json { render json: @questionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionaries/1
  # DELETE /questionaries/1.json
  def destroy
    @questionary.destroy
    respond_to do |format|
      format.html { redirect_to questionaries_url, notice: 'Questionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionary
      @questionary = Questionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionary_params
      params.require(:questionary).permit(:title, :description, :deadline)
    end
end

Rails/p011/app/helpers/questionaries_helper.rb
module QuestionariesHelper
end

Rails/p011/app/views/questionaries/_form.html.erb
<%= form_with(model: questionary, local: true) do |form| %>
  <% if questionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionary.errors.count, "error") %> prohibited this questionary from being saved:</h2>

      <ul>
      <% questionary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :questionary_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :questionary_description %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline, id: :questionary_deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rails/p011/app/views/questionaries/edit.html.erb
<h1>Editing Questionary</h1>

<%= render 'form', questionary: @questionary %>

<%= link_to 'Show', @questionary %> |
<%= link_to 'Back', questionaries_path %>

Rails/p011/app/views/questionaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>トルネード一門わくわくアンケート教室</h1>

<table>
  <!-- 一行目 -->
  <thead>
    <tr>
      <th>タイトル</th>
      <th>期間</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <!-- 二行目以降 -->
  <tbody>
    <!--保存時にutc認識にできないんでしょうかね-->
    <% dx = 60*60*9  # 時差調整項 %>
    <% @questionaries.each do |questionary| %>
      <tr>
        <!--タイトル-->
        <td><%= questionary.title %></td>
        <!--期間-->
        <td><%= "残り" + ((questionary.deadline-DateTime.now-dx)/(60*60*24)).to_i.to_s + "日" %>
        <!--状態表示-->
        <% if questionary.deadline - dx > DateTime.now %>
          <span class="not_finished">受付中</span>
          </td>
          <td><%= link_to '詳細表示', questionary %></td>
        <% else %>
          <span class="finished">終了</span>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新たなるアンケートの生成 ', new_questionary_path %>

Rails/p011/app/views/questionaries/new.html.erb
<h1>New Questionary</h1>

<%= render 'form', questionary: @questionary %>

<%= link_to 'Back', questionaries_path %>

Rails/p011/app/views/questionaries/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title"><%= @questionary.title %></h1>

<div class="questionary">
  <p class="description">
    <%= @questionary.description %>
  </p>
  <p class="deadline">
    <strong>最終時刻</strong>
    <%= @questionary.deadline %>
  </p>
</div>

<div class="items">
  <%= form_tag(action:"show", id:@questionary.id) %>
    <% count_items = 0   # 質問文カウント %>
    <% @questionary.questionary_item.each do |item| %>
      <% count_items += 1 %>
      
      <!-- 質問文 -->
      <p class="q"><%= item.content %></p>

      <% count_choices = 0  # 選択肢カウント%>
      <% item.questionary_choice.each do |choice| %>
        <% count_choices += 1 %>

        <div class="choice">
          <input
            type="radio"
            id="<%= count_items.to_s + '_' + count_choices.to_s %>" 
            name="r<% count_items.to_s %>"
            value="<%= choice.value %>" 
          >
          <label for="<%= count_items.to_s + '_' + count_choices.to_s %>">
            <%= choice.content %>
          </label>
        </div>
      <% end %>
      <hr>
    <% end %>

    <%= submit_tag "送信" %>
  </form>
</div>

<%= link_to '戻る', questionaries_path %>