Rails/p010/config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/p010/app/models/answer.rb
class Answer < ApplicationRecord
    # questionとのアソシエーション
    belongs_to :question

    # バリデーション
    validates :content, :name, presence: {message: "は必ず記されなければならない。"}
end

Rails/p010/app/models/question.rb
class Question < ApplicationRecord
    # answerとのアソシエーション
    has_many :answer

    # バリデーション
    validates :content, :name, presence: {message: "は必ず入力しなければならない。"}
end

Rails/p010/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    #@answers = Answer.all
    redirect_to '/questions'
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    redirect_to '/questions'
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    redirect_to '/questions'
  end

  # POST /answers
  # POST /answers.json
  def create
    end_counter = 10    # 最大可能回答数
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        # 制限到達時処理
        num = Answer.where('question_id = ?', @answer.question_id).count
        if num >= end_counter
          q = Question.find(@answer.question_id)
          q.finished = true
          q.save
        end

        format.html { redirect_to '/questions/' + @answer.question_id.to_s, notice: 'Aは成功裏に創造されしまた。' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
=begin
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
=end
    redirect_to '/questions'
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
=begin
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
=end
    redirect_to '/questions'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :content, :name)
    end
end

Rails/p010/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  layout 'questions'

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order created_at: :desc
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    # Aデータの初期設定
    @answer = Answer.new
    @answer.question_id = params[:id]
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    redirect_to '/questions'
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions', notice: '投の稿をしました。' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
=begin
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
=end
    redirect_to '/questions'
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
=begin
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
=end
    redirect_to '/questions'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :name, :finished)
    end
end

Rails/p010/app/helpers/answers_helper.rb
module AnswersHelper
end

Rails/p010/app/helpers/questions_helper.rb
module QuestionsHelper
end

Rails/p010/app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id, id: :answer_question_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :answer_content %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :answer_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rails/p010/app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

Rails/p010/app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Content</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.content %></td>
        <td><%= answer.name %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

Rails/p010/app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

Rails/p010/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>