Rails/p011/config/routes.rb
Rails.application.routes.draw do
  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get   'questionary_results/calc/:id', to: 'questionary_results#calc'
  get   'questionary_choices/new/:id',  to: 'questionary_choices#new'
  get   'questionary_items/new/:id',    to: 'questionary_items#new'
  post  'questionaries/:id',            to: 'questionaries#sendform'
end

Rails/p011/app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
    # 主データ：質問概要
    belongs_to  :questionary
    # 従データ：選択肢
    has_many    :questionary_choice

    validates :content, presence: {
        message: 'の存在が要請されています。'
    }
end

Rails/p011/app/controllers/questionary_items_controller.rb
class QuestionaryItemsController < ApplicationController
  before_action :set_questionary_item, only: [:show, :edit, :update, :destroy]

  # GET /questionary_items
  # GET /questionary_items.json
  def index
    @questionary_items = QuestionaryItem.all
  end

  # GET /questionary_items/1
  # GET /questionary_items/1.json
  def show
  end

  # GET /questionary_items/new
  def new
    @questionary_item = QuestionaryItem.new
    # 基本情報のセット
    @questionary_item.questionary_id = params[:id]
    @questionary = Questionary.find(params[:id])
  end

  # GET /questionary_items/1/edit
  def edit
  end

  # POST /questionary_items
  # POST /questionary_items.json
  def create
    @questionary_item = QuestionaryItem.new(questionary_item_params)

    respond_to do |format|
      if @questionary_item.save
        format.html { redirect_to '/questionary_choices/new/' + @questionary_item.id.to_s}
        format.json { render :show, status: :created, location: @questionary_item }
      else
        format.html { render :new }
        format.json { render json: @questionary_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionary_items/1
  # PATCH/PUT /questionary_items/1.json
  def update
    respond_to do |format|
      if @questionary_item.update(questionary_item_params)
        format.html { redirect_to @questionary_item, notice: 'Questionary item was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionary_item }
      else
        format.html { render :edit }
        format.json { render json: @questionary_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionary_items/1
  # DELETE /questionary_items/1.json
  def destroy
    @questionary_item.destroy
    respond_to do |format|
      format.html { redirect_to questionary_items_url, notice: 'Questionary item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionary_item
      @questionary_item = QuestionaryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionary_item_params
      params.require(:questionary_item).permit(:content, :questionary_id)
    end
end

Rails/p011/app/helpers/questionary_items_helper.rb
module QuestionaryItemsHelper
end

Rails/p011/app/views/questionary_items/_form.html.erb
<%= form_with(model: questionary_item, local: true) do |form| %>
  <% if questionary_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionary_item.errors.count, "error") %> prohibited this questionary_item from being saved:</h2>

      <ul>
      <% questionary_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :questionary_item_content %>
  </div>

  <div class="field">
    <%= form.label :questionary_id %>
    <%= form.number_field :questionary_id, id: :questionary_item_questionary_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rails/p011/app/views/questionary_items/edit.html.erb
<h1>Editing Questionary Item</h1>

<%= render 'form', questionary_item: @questionary_item %>

<%= link_to 'Show', @questionary_item %> |
<%= link_to 'Back', questionary_items_path %>

Rails/p011/app/views/questionary_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionary Items</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Questionary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionary_items.each do |questionary_item| %>
      <tr>
        <td><%= questionary_item.content %></td>
        <td><%= questionary_item.questionary_id %></td>
        <td><%= link_to 'Show', questionary_item %></td>
        <td><%= link_to 'Edit', edit_questionary_item_path(questionary_item) %></td>
        <td><%= link_to 'Destroy', questionary_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionary Item', new_questionary_item_path %>

Rails/p011/app/views/questionary_items/new.html.erb
<h1>質問の作成</h1>
<p>「<%= @questionary.title %>」について</p>

<%= render 'form', questionary_item: @questionary_item %>
<hr>
<%= link_to 'アンケートに戻る', '/questionaries' %>

Rails/p011/app/views/questionary_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @questionary_item.content %>
</p>

<p>
  <strong>Questionary:</strong>
  <%= @questionary_item.questionary_id %>
</p>

<%= link_to 'Edit', edit_questionary_item_path(@questionary_item) %> |
<%= link_to 'Back', questionary_items_path %>